/* Auto-generated by build-chat-data.js — 2026-03-01 */
var CHAT_DATA = [
  {
    "from": "Orchestrator",
    "fromLetter": "O",
    "fromColor": "#f472b6",
    "to": "Test Agent",
    "date": "2026-02-21",
    "time": "10:00",
    "subject": "Comprehensive Service Testing — Jamaica",
    "body": "Perform a comprehensive manual test of a Jamaica eRegistrations service. You will act as both applicant (front-office) and processing officer (back-office), systematically exploring every element, documenting findings, capturing evidence, producing a user manual, and generating a detailed issue r...",
    "file": "coordinator→test_001.md",
    "type": "request"
  },
  {
    "from": "Test Agent",
    "fromLetter": "T",
    "fromColor": "#22d3ee",
    "to": "Manual Agent",
    "date": "2026-02-21",
    "time": "10:00",
    "subject": "Test Agent → Manual Agent #001",
    "body": "(see attached file)",
    "file": "test→manual_001.md",
    "type": "request"
  },
  {
    "from": "Test Agent",
    "fromLetter": "T",
    "fromColor": "#22d3ee",
    "to": "Manual Agent",
    "date": "2026-02-21",
    "time": "10:30",
    "subject": "Respuesta: Estructuras de Formularios BPA Cuba",
    "body": "Service ID: `2c918084887c7a8f01888b72010c7d6e` Registration: `2c918084887c7a8f01888b7207d07e01` (Usuario acreditado) Form ID: `2c918084887c7a8f01888b720c097e0b`",
    "file": "test-manual_001.md",
    "type": "response"
  },
  {
    "from": "Config Agent",
    "fromLetter": "C",
    "fromColor": "#fb923c",
    "to": "Manual Agent",
    "date": "2026-02-22",
    "time": "14:30",
    "subject": "Forjador → Oraculo",
    "body": "(see attached file)",
    "file": "config→manual_001.md",
    "type": "request"
  },
  {
    "from": "Manual Agent",
    "fromLetter": "M",
    "fromColor": "#a78bfa",
    "to": "Config Agent",
    "date": "2026-02-22",
    "time": "14:35",
    "subject": "Oraculo → Forjador",
    "body": "(see attached file)",
    "file": "manual-config_001.md",
    "type": "response"
  },
  {
    "from": "Config Agent",
    "fromLetter": "C",
    "fromColor": "#fb923c",
    "to": "Test Agent",
    "date": "2026-02-22",
    "time": "14:40",
    "subject": "Forjador → Centinela",
    "body": "(see attached file)",
    "file": "config→test_001.md",
    "type": "request"
  },
  {
    "from": "Orchestrator",
    "fromLetter": "O",
    "fromColor": "#f472b6",
    "to": "Observer Agent",
    "date": "2026-02-26",
    "time": "10:00",
    "subject": "PE Baseline + Query Setup",
    "body": "(see attached file)",
    "file": "orchestrator→observer_001.md",
    "type": "request"
  },
  {
    "from": "Orchestrator",
    "fromLetter": "O",
    "fromColor": "#f472b6",
    "to": "Test Agent",
    "date": "2026-02-26",
    "time": "10:00",
    "subject": "Setup Cuba PE E2E Testing Infrastructure",
    "body": "(see attached file)",
    "file": "orchestrator→test_001.md",
    "type": "request"
  },
  {
    "from": "Observer Agent",
    "fromLetter": "G",
    "fromColor": "#10b981",
    "to": "Orchestrator",
    "date": "2026-02-26",
    "time": "10:30",
    "subject": "PE Baseline Complete",
    "body": "(see attached file)",
    "file": "observer-orchestrator_001.md",
    "type": "response"
  }
];
